# Generated by Django 4.2.2 on 2023-07-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_newsstory_category'),
        ('users', '0002_customuser_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourited_by', to='news.newsstory'),
        ),
    ]
