# Generated by Django 4.2.2 on 2023-07-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('change_date', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('World', 'World'), ('Business', 'Business'), ('Sport', 'Sport'), ('Science', 'Science'), ('Entertainment', 'Entertainment')], default='World', max_length=20)),
                ('image_url', models.CharField(default='placeholder-3.jpg', max_length=200)),
                ('content', models.TextField()),
            ],
        ),
    ]
