# Generated by Django 4.2.2 on 2023-07-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsstory_change_date_alter_newsstory_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='category',
            field=models.CharField(choices=[('World', 'World'), ('Business', 'Business'), ('Sport', 'Sport'), ('Science', 'Science'), ('Entertainment', 'Entertainment')], default='World', max_length=20),
        ),
    ]
