# Generated by Django 4.2.2 on 2023-07-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_newsstory_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='category',
            field=models.CharField(choices=[('World', 'World'), ('Business', 'Business'), ('Sport', 'Sport'), ('Science', 'Science'), ('Technology', 'Technology'), ('Entertainment', 'Entertainment')], default='World', max_length=20),
        ),
    ]
